#Assignment 1

print('\t\t\t\tWORLD CUP \"CRICKET\"-2019')
print('\t\t\t\t-------------------------')
print('\n\t\t\t\t\tTEAMS')
print('\t\t\t\t\t*****')
print('\n\t\tC.No. \t\t\tCOUNTRY \t\tCAPTAIN ')
print('\t\t--------------------------------------------------------')
print('\n\t\t1 \t\t\t\'INDIA\' \t\tVIRAT KHOLI')
print('\n\t\t2 \t\t\t\'AUSTRALIA\' \t\tAARON FINCH')
print('\n\t\t3 \t\t\t\'NEW ZEALAND\' \t\tKANE WILLIAMSON')
print('\n\t\t4 \t\t\t\'SOUTH AFRICA\'\t\tFAF DU PLESSIS')
print('\n\t\t5 \t\t\t\'WEST INDIES\' \t\tDARREN SAMMY')
print('\n\n\t\t\t\t\t**************')
print('\n\n\tALL THE BEST \'INDIA\'')
print('\n\t\t\t\t\t\t\tBY:')
print('\n\t\t\t\t\t\t\t\\JAHNAVI S RAO\\')
print('\n\t\t\t\t\t\t\tDATE:')